CUR_DIR=$(pwd)
docker rm -f $(cat ${CUR_DIR}/docker.pid)

# CGO_ENABLED=0;POSTGRES_RECIPE_DBNAME=db_test;POSTGRES_RECIPE_HOST=localhost;POSTGRES_RECIPE_PORT=5432;POSTGRES_RECIPE_USER=test_user

export POSTGRES_RECIPE_HOST=localhost
export POSTGRES_RECIPE_PORT=5432
export POSTGRES_RECIPE_DBNAME="db_lab"
export POSTGRES_RECIPE_USER="lab"
docker run -i --name pg_lab -p $POSTGRES_RECIPE_PORT:$POSTGRES_RECIPE_PORT -e POSTGRES_USER=$POSTGRES_RECIPE_USER -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=$POSTGRES_RECIPE_USER -e POSTGRES_DB=$POSTGRES_RECIPE_DBNAME -d postgres >${CUR_DIR}/docker.pid

# psql -h localhost -p 5432 -U lab -d db_lab

